# Generated by Django 4.2.4 on 2023-08-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen_magic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.DurationField(default='HH:MM:SS'),
        ),
    ]
